# https://megalinter.io/latest/json-schemas/configuration.html
ENABLE_LINTERS:
  - CSHARP_CSHARPIER
  - TSX_ESLINT
  - TYPESCRIPT_ES
  - TYPESCRIPT_PRETTIER
  - YAML_PRETTIER
  - YAML_V8R
  - JSON_PRETTIER
  - JSON_V8R
  - DOCKERFILE_HADOLINT
  - MARKDOWN_MARKDOWNLINT
  - MARKDOWN_MARKDOWN_LINK_CHECK
  - MARKDOWN_REMARK_LINT
  - MARKDOWN_MARKDOWN_TABLE_FORMATTER

TSX_ESLINT_RULES_PATH: /frontend
TYPESCRIPT_ES_RULES_PATH: /frontend
