# ABDEVOPS

services:
    # Frontend Service
    product.frontend:
        image: alihmohammad/devops-frontend:${TAG}
        restart: always
        container_name: frontend-container
        ports:
            - "8080:3000"

    # Backend Service
    product.backend:
        image: alihmohammad/devops-backend:${TAG}
        container_name: backend-container
        restart: always
        ports:
            - "8081:8080"
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - ConnectionString=Server=database-container;Database=devops_db;User=root;Password=${MYSQL_PASSWORD};SslMode=None;
            - ASPNETCORE_URLS=http://0.0.0.0:8080;
            - JWT_KEY=d6b3dbd74df79c21f57d64de24ac1f0855941d19e7deb6d6d4d500f6dab077b7;
            - WEATHER_API_KEY=56bf961a0ee5487285573509242009
        depends_on:
          product.db:
            condition: service_healthy

    # Database Service
    product.db:
        image: mysql:5.7
        container_name: database-container # name of container
        restart: always # always restart
        environment:
            MYSQL_DATABASE: "devops_db" # name of database
            MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD} # password for root user
        ports:
            - "3306:3306" # host port 3306 is mapper to docker port 3306
        volumes:
            - DEVOPS:/var/lib/mysql
        healthcheck:
          test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${MYSQL_PASSWORD}"]
          timeout: 20s
          retries: 10
          start_period: 10s

volumes:
    DEVOPS:
