# ABDEVOPS

services:
  # Frontend Service
  product.frontend:
    image: alihmohammad/devops-frontend:${TAG}
    restart: always
    container_name: frontend-container

  # Backend Service
  product.backend:
    image: alihmohammad/devops-backend:${TAG}
    container_name: backend-container
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionString=Server=database-container;Database=devops_db;User=root;Password=${MYSQL_PASSWORD};SslMode=None;
      - ASPNETCORE_URLS=http://0.0.0.0:8080;
      - JWT_KEY=${JWT_KEY};
      - WEATHER_API_KEY=${WEATHER_KEY}
    depends_on:
      product.db:
        condition: service_healthy

  # Database Service
  product.db:
    image: mysql:5.7
    container_name: database-container
    restart: always
    environment:
      MYSQL_DATABASE: "devops_db" # name of database
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD} # password for root user
    ports:
      - "3307:3306"
    volumes:
      - DEVOPS:/var/lib/mysql
    healthcheck:
      test:
        ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${MYSQL_PASSWORD}"]
      timeout: 20s
      retries: 10
      start_period: 10s

  # Nginx Service
  nginx:
    image: nginx:latest
    container_name: nginx-container
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf # Mount the custom Nginx config
      - /etc/letsencrypt/live/abdevops.dk/:/etc/letsencrypt/live/abdevops.dk
      - /etc/letsencrypt/archive/abdevops.dk/:/etc/letsencrypt/archive/abdevops.dk
    depends_on:
      - product.frontend
      - product.backend

volumes:
  DEVOPS:
