name: Pull Request

permissions:
  actions: write
  pull-requests: write
  deployments: write
  contents: write
  checks: write

on:
  pull_request:

jobs:
  call-tests:
    name: Run Tests
    uses: ./.github/workflows/tests.yaml

