name: Push to Main Branch

permissions:
  actions: write
  pull-requests: write
  deployments: write
  contents: write
  checks: write

on:
  push:
    branches:
      - main

jobs:
  call-tests:
    name: Run Tests
    uses: ./.github/workflows/tests.yaml
