name: "Super Linter"

permissions:
  contents: read
  packages: read
  statuses: write

on: 
  workflow_call:
  workflow_dispatch:
  pull_request: 

jobs: 
  Super-lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 

    - name: Initiate linting
      uses: super-linter/super-linter@v7.1.0
      env:
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
