name: Tag Release

on:
  push:
    tags:
      - "*"

jobs:
  push-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend # Location of Dockerfile
          push: true # Push to Docker Hub
          tags: alihmohammad/devops-frontend:${{ github.ref_name }} # Tags image with github tag from repo
