name: Tests

permissions:
  actions: write
  pull-requests: write
  deployments: write
  contents: write
  checks: write

on:
  workflow_call:

jobs:
  test-backend:
    name: Test and build backend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.x"

      - name: Run Tests
        working-directory: ./backend
        run: |
          dotnet test --logger 'trx;LogFileName=TestResults.trx' \
          --verbosity normal --results-directory ./_test-results

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: ./backend/_test-results/TestResults.trx

      - name: Build Application # Is the application buildable
        working-directory: ./backend
        run: dotnet build api
